### ISSUE TITLE
Invalid example

### ISSUE THREAD

**Issue by Surasi-Jui** [vijendra1125/Tensorfow_Object_detection_API-Custom_Mask_RCNN#22] opened 2019-12-02 16:07 UTC
Hello, @vijendra1125 
I follow your tutorial in https://medium.com/@vijendra1125/custom-mask-rcnn-using-tensorflow-object-detection-api-101149ce0765 
and found problem in create tfrecord file with this

I1202 22:53:40.941998 139788826822464 create_mask_rcnn_tf_record.py:213] On image 0 of 32
W1202 22:53:40.948963 139788826822464 create_mask_rcnn_tf_record.py:228] Invalid example: /home/tensorflow_for_train_mask/models/research/object_detection/dataset/JPEGImages/image10.jpg, ignoring.
W1202 22:53:40.952089 139788826822464 create_mask_rcnn_tf_record.py:228] Invalid example: /home/tensorflow_for_train_mask/models/research/object_detection/dataset/JPEGImages/image30.jpg, ignoring.
W1202 22:53:40.955887 139788826822464 create_mask_rcnn_tf_record.py:228] Invalid example: /home/tensorflow_for_train_mask/models/research/object_detection/dataset/JPEGImages/image17.jpg, ignoring.

Would you give some suggestion please?

**Comment by tealeeseng** [comment] 2019-12-20 08:59
Managed to train after following 2 changes in object_detection/dataset_tools/create_mask_rcnn_tf_record.py

`1st one, inside main()`
`__________`
`  label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path) # comment out following 3 lines.`
`  # for key in label_map_dict.keys():`
`  #   label_map_dict[key] = [label_map_dict[key], key[-3:]]`
`  #   label_map_dict[key[:-3]] = label_map_dict.pop(key)`
`_________`

`2nd one, inside image_to_tf_data()`
`__________`
`  if(True == FLAGS.use_xmls):`
`...`
`  else:`
`      for key in label_map_dict.keys():`
`          class_name = key`
`          # pixel_val = int(label_map_dict[class_name][1]) # remove [1]`
`          pixel_val = int(label_map_dict[class_name])`
``
``

**Comment by tealeeseng** [comment] 2019-12-20 09:12
[create_mask_rcnn_tf_record.txt](https://github.com/vijendra1125/Custom-Mask-RCNN-using-Tensorfow-Object-detection-API/files/3987549/create_mask_rcnn_tf_record.txt)

**Comment by Rutvik21** [comment] 2020-01-20 11:14
1. Instead of commenting the 3 lines, you can also do this: (repeat for every keys defined in label.pbtxt)
key = "name of the key"
label_map_dict[key] = [label_map_dict[key], key[-3:]]
label_map_dict[key[:-3]] = label_map_dict.pop(key)

**Comment by vijendraxsingh** [comment] 2020-01-25 13:08
Is there a specific reason for not editing label.pbtxt as described in the blog post for this repo? If you edit label.pbtxt correctly then you should not have any problem. I am copying instruction from blog post below in case you missed it:
"In the label map, you need to provides one item for each class. Each item holds the following information: class id, class name and the pixel value of the color assigned to the class in masks. You need to notice in the given sample label.pbtxt that the last three letters of the string assigned as name of the class will be considered as the pixel value. You could find the mask pixel value by opening the mask image as a grayscale image and then check pixel value in the area where your object is. A file with name Check_pixel_values.ipynb is given under subfolder named as supporting_script to help you with this task."

**Comment by Rutvik21** [comment] 2020-01-25 13:57
> Is there a specific reason for not editing label.pbtxt as described in the blog post for this repo? If you edit label.pbtxt correctly then you should not have any problem. I am copying instruction from blog post below in case you missed it:
> "In the label map, you need to provides one item for each class. Each item holds the following information: class id, class name and the pixel value of the color assigned to the class in masks. You need to notice in the given sample label.pbtxt that the last three letters of the string assigned as name of the class will be considered as the pixel value. You could find the mask pixel value by opening the mask image as a grayscale image and then check pixel value in the area where your object is. A file with name Check_pixel_values.ipynb is given under subfolder named as supporting_script to help you with this task."

I believe the problem is in the for loop of create_mask_rcnn_tfrecord.py file - 
label_map_dict = label_map_util.get_label_map_dict(FLAGS.label_map_path)
  for key in label_map_dict.keys():
    label_map_dict[key] = [label_map_dict[key], key[-3:]]
    label_map_dict[key[:-3]] = label_map_dict.pop(key)


First pass is successfully completed but in the second pass they keys are taken from the latest label_map_dict.keys() and because of that the following error generated:
![Screenshot (60)](https://user-images.githubusercontent.com/29560869/73122216-4604d980-3fa8-11ea-92f9-aa008edf90a7.png)
As shown in the above figure, the upper part is my label.pbtxt file, and it gives the followed key error.

Also notice the printed line above the Traceback-
W0119 09:58:19..... which is the generated dictionary-label_map_dict after the for loop has executed.

Tell me if I am interpreting something wrong.

Thank you.

**Comment by vijendraxsingh** [comment] 2020-01-26 14:02
Hi @Rutvik21 , Thanks for clarifying the issue. Fix has been pushed.
Please confirm that problem has been resolved and then I will close this issue

**Closed as completed** 2020-05-23 03:35 UTC
Labels: bug
